apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ecommerce
  name: proxy-client
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: proxy-client
  template:
    metadata:
      labels:
        app: proxy-client
    spec:
      automountServiceAccountToken: false
      containers:
      - name: proxy-client
        image: selimhorri/proxy-client-ecommerce-boot:0.1.0
        ports:
        - containerPort: 8900
          protocol: TCP
        
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "dev"
        - name: SPRING_ZIPKIN_BASE_URL
          value: "http://zipkin.ecommerce.svc.cluster.local:9411"
        - name: SPRING_CONFIG_IMPORT
          value: "optional:configserver:http://cloud-config.ecommerce.svc.cluster.local:9296/"
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: "http://service-discovery.ecommerce.svc.cluster.local:8761/eureka/"
        - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
          value: "true"
        - name: EUREKA_INSTANCE_HOSTNAME
          value: "proxy-client"
        
        readinessProbe:
          httpGet:
            path: /proxy-client/actuator/health
            port: 8900
          initialDelaySeconds: 180
          periodSeconds: 20
          timeoutSeconds: 5
          failureThreshold: 8
        
        livenessProbe:
          httpGet:
            path: /proxy-client/actuator/health
            port: 8900
          initialDelaySeconds: 240
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 5
      
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  namespace: ecommerce
  name: proxy-client
spec:
  selector:
    app: proxy-client
  ports:
  - name: http
    port: 8900
    targetPort: 8900
    protocol: TCP
  type: ClusterIP
