apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ecommerce
  name: shipping-service
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: shipping-service
  template:
    metadata:
      labels:
        app: shipping-service
    spec:
      automountServiceAccountToken: false
      containers:
      - name: shipping-service
        image: pablofpp/shipping-service:0.1.0
        ports:
        - containerPort: 8600
          protocol: TCP
        resources:
          requests:
            cpu: "50m"
            memory: "128Mi"
          limits:
            cpu: "300m"
            memory: "384Mi"
        
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "dev"
        - name: JAVA_TOOL_OPTIONS
          value: "-Xms64m -Xmx192m -XX:MaxRAMPercentage=50"
        - name: SPRING_ZIPKIN_BASE_URL
          value: "http://zipkin.ecommerce.svc.cluster.local:9411"
        - name: SPRING_CONFIG_IMPORT
          value: "optional:configserver:http://cloud-config.ecommerce.svc.cluster.local:9296/"
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: "http://service-discovery.ecommerce.svc.cluster.local:8761/eureka/"
        - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
          value: "true"
        - name: EUREKA_INSTANCE_HOSTNAME
          value: "shipping-service"
        
        readinessProbe:
          httpGet:
            path: /shipping-service/actuator/health
            port: 8600
          initialDelaySeconds: 180
          periodSeconds: 20
          timeoutSeconds: 5
          failureThreshold: 8
        
        livenessProbe:
          httpGet:
            path: /shipping-service/actuator/health
            port: 8600
          initialDelaySeconds: 240
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 5
      
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  namespace: ecommerce
  name: shipping-service
spec:
  selector:
    app: shipping-service
  ports:
  - name: http
    port: 8600
    targetPort: 8600
    protocol: TCP
  type: ClusterIP