
version: '3'
services:
  shipping-service-container:
    image: pablofpp/shipping-service-ecommerce-boot
    ports:
      - 8600:8600
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    networks:
      - microservices_network



